config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'hubs/index', as: :hubs
  get 'hubs/closets', to: 'hubs#closest'
  
  get 'hubs/autocomplete_address', to: 'hubs#autocomplete_address'

  root to: "hubs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/country.rb
class Country < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :code, presence: true, uniqueness: true
end

app/models/function.rb
class Function < ApplicationRecord
  CODES = %w[0 1 2 3 4 5 6 7 B]

  validates :code, presence: true,
                   uniqueness: { scope: :hub_id },
                   inclusion: { in: CODES }

  belongs_to :hub

  def self.explanation(code)
    case code
    when '1'
      'Port (for any kind of waterborne transport)'
    when '2'
      'Rail terminal'
    when '3'
      'Road terminal'
    when '4'
      'Airport'
    when '5'
      'Postal exchange office'
    when '6'
      'Inland Clearance Depot – ICD or "Dry Port", "Inland Clearance Terminal", etc.'
    when '7'
      'Fixed transport functions (e.g. oil platform)"; the classifier "7" is reserved for this function. Noting that the description "oil pipeline terminal" would be more relevant, and could be extended to cover also electric power lines and ropeway terminals.'
    when 'B'
      'Border crossing function'
    when '0'
      'Function not known, to be specified'
    end
  end
end

app/models/function_hub.rb
class FunctionHub < ApplicationRecord
  validates :code, uniqueness: { scope: :hub_id },
                   inclusion: { in: %w[0 1 2 3 4 5 6 7 B] },
                   presence: true
  belongs_to :hub
end

app/models/hub.rb
class Hub < ApplicationRecord
  STATUSES = %w[AA AC AF AI AM AQ AS RL RN RQ UR RR QQ XX]
  CHANGE_CODES = %w[X # ¦ + = !]

  validates :change_code, inclusion: {in: CHANGE_CODES}, allow_nil: true
  validates :unlocode, presence:true
  validates :code, presence: true
  validates :name, presence: true
  validates :name_wo_diacritics, presence: true
  validates :status, inclusion: { in: STATUSES }, allow_nil: true

  belongs_to :country
  has_one :location
  has_many :functions, -> { order(:code) }

  def self.change_code_explanation(change_code)
    case change_code
    when 'X'
      'Marked for deletion in the next issue'
    when '#'
      'Change in location name (usually spelling)'
    when '¦'
      'Other changes in the entry (not location)'
    when '+'
      'Entry added to the current issue'
    when '='
      'Reference entry'
    when '!'
      'Retained for certain entries in the USA code list ("controlled duplications")'
    end
  end

  def self.status_explanation(status)
    case status
    when 'AA'
      'Approved by competent national government agency'
    when 'AC'
      'Approved by Customs Authority'
    when 'AF'
      'Approved by national facilitation body'
    when 'AI'
      'Code adopted by international organisation (IATA or ECLAC)'
    when 'AM'
      'Approved by the UN/LOCODE Maintenance Agency'
    when 'AQ'
      'Entry approved, functions not verified'
    when 'AS'
      'Approved by national standardisation body'
    when 'RL'
      'Recognised location - Existence and representation of location name confirmed by check against nominated gazetteer or other reference work'
    when 'RN'
      'Request from credible national sources for locations in their own country'
    when 'RQ'
      'Request under consideration'
    when 'UR'
      "Entry included on user's request; not officially approved"
    when 'RR'
      'Request rejected'
    when 'QQ'
      'Original entry not verified since date indicated'
    when 'XX'
      'Entry that will be removed from the next issue of UN/LOCODE'
    end
  end
end

app/models/location.rb
class Location < ApplicationRecord
  validates :longlat, presence: true
  
  belongs_to :hub
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/hubs/index_search.rb
class Hubs::IndexSearch
  def initialize(params)
    @params = params
    @base_rel = Hub.all
  end

  def results
    return @base_rel if @params.blank?
    filter_unlocode
    filter_name
    filter_check_boxes(:change_code)
    filter_check_boxes(:status)
    filter_functions
    order
    @base_rel
  end

  private


  def filter_functions
    return if @params[:functions].blank?
    @base_rel = @base_rel.distinct
    if false_checkbox?(@params[:functions_and])
      or_functions_filter
    else
      and_function_filter
    end
  end

  def or_functions_filter
    @base_rel = @base_rel
      .joins(:functions)
      .where(functions: {code: @params[:functions]})
  end

  def and_function_filter
    @params[:functions].each do |function_code|
      select_hub_id = Function.where(code: function_code).select(:hub_id)
      @base_rel = @base_rel.where(id: select_hub_id)
    end
  end

  def filter_unlocode
    return if @params[:unlocode].blank?
    @base_rel = @base_rel.where(unlocode: @params[:unlocode].upcase)
  end

  def filter_name
    return if @params[:name_wo_diacritics].blank?
    name = Hub.arel_table[:name_wo_diacritics]
    @base_rel = @base_rel.where(name.matches("%#{@params[:name_wo_diacritics]}%"))
  end

  def filter_check_boxes(key)
    param_value = @params[key.to_s.pluralize.to_sym]
    return if param_value.blank?
    @base_rel = @base_rel.where("#{key}": param_value)
  end
  
  def order
    if @params[:order_by] == 'country'
      @base_rel = @base_rel.joins(:country).order("countries.name #{order_asc_desc}")
    else
      @base_rel = @base_rel.order("name_wo_diacritics #{order_asc_desc}")
    end
  end
  
  
  def order_asc_desc
    false_checkbox?(@params[:order_desc]) ? 'ASC' : 'DESC'
  end
  
  def false_checkbox?(param_value)
    param_value.blank? || param_value == '0'
  end
end

app/controllers/hubs_controller.rb
class HubsController < ApplicationController
  def index
    @hubs = Hubs::IndexSearch
              .new(index_filter_params)
              .results
              .paginate(:page => params[:page])
              .preload(:functions, :location, :country)

  end

  def closest
    lat = address_params[:lat]
    long = address_params[:long]
    if !lat.blank? && !long.blank?
      @hubs = Hub
        .joins(:location)
        .order("ST_Distance(locations.longlat, ST_MakePoint(#{long.to_f}, #{lat.to_f}))")
        .limit(1)
    else
      @hubs = []
    end
  end

  def autocomplete_address
    res =  Geocoder.search(params[:term]).map do |geocoder|
      {value: geocoder.address, data: geocoder.coordinates}
    end
    render json: res
  end

  private

  def index_filter_params
    params.fetch(:filter, {})
  end
  
  def address_params
    params.fetch(:address, {})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hubs_helper.rb
module HubsHelper
  def form_for_object_from_param(param)
    form_for_params = params.fetch(param, {})
    form_for_requirements = { model_name: { param_key: param } }

    JSON.parse(form_for_params.merge(form_for_requirements).to_json, object_class: OpenStruct)
  end
end

app/views/hubs/_hub.html.slim
tr
  td = hub.change_code_humane
  td = hub.country.name
  td = hub.unlocode
  td = hub.name
  td = hub.name_wo_diacritics
  td = hub.subdiv
  td
    ul
      - hub.functions.each do |function|
        li = function.decorate.humane
  td = hub.status_humane
  td = hub.uploaded_date&.strftime("%Y %b")
  td = hub.iata
  td = hub.location&.decorate&.humane
  td = hub.remark
  td = hub.location&.decorate&.map_link

app/views/hubs/_hubs_table.html.slim
table border="1"
  tr
    th Change code
    th Country
    th UNLOCODE
    th Name
    th Name without diacritics
    th Subdivision
    th Function
    th Status
    th Date
    th IATA
    th Coordinates(lat, long)
    th Remarks
    th Show on map
  - @hubs.decorate.each do |hub|
    = render hub

app/views/hubs/closest.html.slim
h4 = link_to 'Go to the hubs search', hubs_path

h1 Find the closest hub

= form_for(form_for_object_from_param(:address), method: :get, url: hubs_closets_path) do |f|
  
  = f.autocomplete_field :name, hubs_autocomplete_address_path, size: 95
  = f.hidden_field :lat
  = f.hidden_field :long

  = submit_tag 'Find'

- if @hubs.empty?
  p No correct address is provided
- else
  = render 'hubs_table'

app/views/hubs/index.html.slim
h4 = link_to 'Go to the closest hub search', hubs_closets_url

h1 Hubs search

= form_for(form_for_object_from_param(:filter), method: :get, url: hubs_path) do |f|
  p
    = f.label :change_codes
    - Hub::CHANGE_CODES.each do |change_code|
      = f.check_box :change_codes, { multiple: true }, change_code, nil
      abbr title=Hub.change_code_explanation(change_code)
        = change_code
  p
    = f.label :unlocode
    = f.text_field :unlocode
  p
    = f.label :name_wo_diacritics, 'Name (without diacritics)'
    = f.text_field :name_wo_diacritics
  p
    = f.label :statuses
    - Hub::STATUSES.each do |status|
      = f.check_box :statuses, { multiple: true }, status, nil
      abbr title=Hub.status_explanation(status)
        = status
  p
    = f.label :functions
    - Function::CODES.each do |code|
      = f.check_box :functions, { multiple: true }, code, nil
      abbr title=Function.explanation(code)
        = code
  p
    = f.label :functions_and, title: 'Show hubs with all selected functions'
    = f.check_box :functions_and

  p
    = f.label :order_by
    = f.select :order_by, [['name (without diacritics)', 'name'], ['country', 'country']]
  p
    = f.label :order_desc
    = f.check_box :order_desc
  = f.submit 'Show hubs'


- if @hubs.empty?
  p No hubs are found
- else
  = will_paginate @hubs
  = render 'hubs_table'
  = will_paginate @hubs

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Itsmycargotest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>